`define MEM_PSRAM
`define DEF_ADDR_WIDTH 21
`define SRAM_DATA_WIDTH_64
`define DEF_SRAM_DATA_WIDTH 64
`define DEF_BURST_WRITE_LENGTH 128
`define DEF_BURST_READ_LENGTH 128
`define WR_VIDEO_WIDTH_24
`define DEF_WR_VIDEO_WIDTH 24
`define RD_VIDEO_WIDTH_24
`define DEF_RD_VIDEO_WIDTH 24
`define DEF_IMAGE_SIZE 32'h00800000
`define USE_THREE_FRAME_BUFFER
`define WRITE_FIFO_DEPTH_2048
`define DEF_WRITE_FIFO_DEPTH 2048
`define READ_FIFO_DEPTH_2048
`define DEF_READ_FIFO_DEPTH 2048
