-d E:\TangNano\tangnano9k-vfb-psram\impl\gwsynthesis\VFB_PSRAM_RefDesign.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\TangNano\tangnano9k-vfb-psram\src\VFB_PSRAM_RefDesign.cst
-cfg E:\TangNano\tangnano9k-vfb-psram\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
